apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: busybox-hpa
spec:
  scaleTargetRef:
     apiVersion: apps/v1
     kind: Deployment
     name: livenessprobe
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: utilization
          averageUtilization: 60



