apiVersion: apps/v1
kind: Deployment
metadata:
  name: livenessprobe
spec:
  replicas: 1
  selector:
    matchLabels:
        app: live1
  template:
    metadata:
      labels:
        app: live1
    spec:
      containers:
        - name: busyboxcontainer
          image: busybox:latest
          command: 
             - sh
             - -c
             - |
               sleep 20
               touch /tmp/started
               touch /tmp/ready
               touch /tmp/live
               sleep 3600
          startupProbe:
            exec:
              command:
                - cat
                - /tmp/started
            failureThreshold: 10
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/ready
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          



